### ISSUE TITLE
Using alternative EEG Cap for Synchronization Likelihood

### ISSUE THREAD

**Issue by kimberlylray** [guiomar/HERMES#3]
I am interested in estimating the SL at rest, however the EEG cap we use is not one of the defaults provided in HERMES.  
We are using an 64 channel Acticap, and the polar/spherical coordinate are provided in the attached file.  
I can convert the coordinates into cartesian space, but they do not seems to be in similar spaces as other coordinate positions provided in Hermes. 
Do you have a suggestion for how to best incorporate our cap with HERMES? 
Many thanks!
[CMA-64_NO_REF.bvef.zip](https://github.com/guiomar/HERMES/files/2774458/CMA-64_NO_REF.bvef.zip)

**Comment by guiomar** [comment]
Hi @kimberlylray, 

Sorry for the delay. I'm currently on maternity leave, but my colleague Ricardo Bruña updated the systems.m file under the Coordinates folder to include the Acticap 64 system you provided.
There's an option with and without the ground.
I have updated it here. Give it a try and let us know if it works.

Cheers,

**Comment by kimberlylray** [comment]
Thanks @guiomar !
